# Generated by Django 4.2.29 on 2026-04-04 01:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código de Pedido')),
                ('gestion', models.PositiveIntegerField(help_text='Año o gestión del pedido (ej: 2024)', verbose_name='Gestión/Año')),
                ('tipo_pedido', models.CharField(choices=[('completo', 'Conjunto Completo'), ('parcial', 'Pedido Parcial')], default='parcial', max_length=20, verbose_name='Tipo de Pedido')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega Estimada')),
                ('notas', models.TextField(blank=True, verbose_name='Notas del Pedido')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('tipo_prenda', models.CharField(choices=[('chamarra', 'Chamarra'), ('buso', 'Buso'), ('polera', 'Polera'), ('short', 'Short')], max_length=20, verbose_name='Tipo de Prenda')),
                ('genero', models.CharField(choices=[('varon', 'Varón'), ('mujer', 'Mujer'), ('unisex', 'Unisex')], max_length=10, verbose_name='Género')),
                ('talla', models.CharField(choices=[('4', '4'), ('6', '6'), ('8', '8'), ('10', '10'), ('12', '12'), ('14', '14'), ('16', '16'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=5, verbose_name='Talla')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('es_parte_de_conjunto', models.BooleanField(default=False, help_text='Indica si este ítem fue generado automáticamente de un conjunto', verbose_name='Es parte de conjunto')),
                ('conjunto_padre_id', models.PositiveIntegerField(blank=True, help_text='ID del ítem conjunto que generó esta prenda', null=True, verbose_name='ID del Conjunto Padre')),
                ('notas', models.CharField(blank=True, max_length=200, verbose_name='Notas')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Ítem de Pedido',
                'verbose_name_plural': 'Ítems de Pedido',
                'ordering': ['tipo_prenda', 'genero', 'talla'],
            },
        ),
        migrations.CreateModel(
            name='ImportacionExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('archivo', models.FileField(upload_to='importaciones/%Y/%m/', verbose_name='Archivo Excel')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('filas_procesadas', models.PositiveIntegerField(default=0, verbose_name='Filas Procesadas')),
                ('filas_con_error', models.PositiveIntegerField(default=0, verbose_name='Filas con Error')),
                ('errores_detalle', models.JSONField(blank=True, default=dict, verbose_name='Detalle de Errores')),
                ('procesado_en', models.DateTimeField(blank=True, null=True, verbose_name='Procesado el')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importaciones', to='pedidos.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Importación Excel',
                'verbose_name_plural': 'Importaciones Excel',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ConjuntoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('genero', models.CharField(choices=[('varon', 'Varón'), ('mujer', 'Mujer'), ('unisex', 'Unisex')], max_length=10, verbose_name='Género')),
                ('talla', models.CharField(choices=[('4', '4'), ('6', '6'), ('8', '8'), ('10', '10'), ('12', '12'), ('14', '14'), ('16', '16'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=5, verbose_name='Talla')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de Conjuntos')),
                ('notas', models.CharField(blank=True, max_length=200, verbose_name='Notas')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conjuntos', to='pedidos.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Conjunto de Pedido',
                'verbose_name_plural': 'Conjuntos de Pedido',
                'ordering': ['genero', 'talla'],
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['codigo'], name='pedidos_ped_codigo_ea9420_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['cliente', 'gestion'], name='pedidos_ped_cliente_633fc7_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado'], name='pedidos_ped_estado_20cbc4_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['fecha_entrega'], name='pedidos_ped_fecha_e_2901ab_idx'),
        ),
        migrations.AddIndex(
            model_name='itempedido',
            index=models.Index(fields=['pedido', 'tipo_prenda'], name='pedidos_ite_pedido__7ea721_idx'),
        ),
        migrations.AddIndex(
            model_name='itempedido',
            index=models.Index(fields=['pedido', 'genero'], name='pedidos_ite_pedido__7b8c58_idx'),
        ),
        migrations.AddIndex(
            model_name='itempedido',
            index=models.Index(fields=['pedido', 'talla'], name='pedidos_ite_pedido__9767ed_idx'),
        ),
        migrations.AddIndex(
            model_name='itempedido',
            index=models.Index(fields=['tipo_prenda', 'genero', 'talla'], name='pedidos_ite_tipo_pr_caaeef_idx'),
        ),
    ]
