# Generated by Django 4.2.29 on 2026-04-04 01:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(help_text='Nombre completo del colegio o institución', max_length=200, verbose_name='Nombre del Cliente')),
                ('tipo', models.CharField(choices=[('colegio', 'Colegio'), ('instituto', 'Instituto'), ('universidad', 'Universidad'), ('empresa', 'Empresa'), ('otro', 'Otro')], default='colegio', max_length=20, verbose_name='Tipo de Cliente')),
                ('contacto_nombre', models.CharField(blank=True, max_length=150, verbose_name='Nombre del Contacto')),
                ('contacto_cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo del Contacto')),
                ('telefono', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^[\\d\\s\\-\\+\\(\\)]+$', 'Ingrese un número de teléfono válido')], verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('nit', models.CharField(blank=True, help_text='Número de identificación tributaria', max_length=20, verbose_name='NIT/CI')),
                ('notas', models.TextField(blank=True, verbose_name='Notas Adicionales')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='clientes_cl_nombre_c231de_idx'), models.Index(fields=['activo'], name='clientes_cl_activo_b76065_idx')],
            },
        ),
    ]
