# Generated by Django 4.2.29 on 2026-04-04 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código de Orden')),
                ('gestion', models.PositiveIntegerField(verbose_name='Gestión/Año')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_corte', 'En Corte'), ('en_confeccion', 'En Confección'), ('en_acabados', 'En Acabados'), ('completada', 'Completada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin_estimada', models.DateField(verbose_name='Fecha de Fin Estimada')),
                ('notas', models.TextField(blank=True, verbose_name='Notas de Producción')),
                ('pedidos', models.ManyToManyField(related_name='ordenes_produccion', to='pedidos.pedido', verbose_name='Pedidos Incluidos')),
            ],
            options={
                'verbose_name': 'Orden de Producción',
                'verbose_name_plural': 'Órdenes de Producción',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='MateriaPrimaRequerida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('tipo_material', models.CharField(choices=[('tela', 'Tela'), ('hilo', 'Hilo'), ('elastico', 'Elástico'), ('botones', 'Botones'), ('cremalleras', 'Cremalleras'), ('etiquetas', 'Etiquetas'), ('bolsas', 'Bolsas de Empaque'), ('otros', 'Otros')], max_length=20, verbose_name='Tipo de Material')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('cantidad_requerida', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Requerida')),
                ('unidad_medida', models.CharField(max_length=20, verbose_name='Unidad de Medida')),
                ('cantidad_comprada', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad Comprada')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('orden_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materia_prima', to='produccion.ordenproduccion', verbose_name='Orden de Producción')),
            ],
            options={
                'verbose_name': 'Materia Prima Requerida',
                'verbose_name_plural': 'Materias Primas Requeridas',
                'ordering': ['tipo_material'],
            },
        ),
        migrations.CreateModel(
            name='ResumenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_prenda', models.CharField(max_length=20, verbose_name='Tipo de Prenda')),
                ('genero', models.CharField(max_length=10, verbose_name='Género')),
                ('talla', models.CharField(max_length=5, verbose_name='Talla')),
                ('cantidad_total', models.PositiveIntegerField(default=0, verbose_name='Cantidad Total')),
                ('orden_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumen_items', to='produccion.ordenproduccion', verbose_name='Orden de Producción')),
            ],
            options={
                'verbose_name': 'Resumen de Producción',
                'verbose_name_plural': 'Resúmenes de Producción',
                'ordering': ['tipo_prenda', 'genero', 'talla'],
                'unique_together': {('orden_produccion', 'tipo_prenda', 'genero', 'talla')},
            },
        ),
    ]
