# Generated by Django 4.2.29 on 2026-04-12 00:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre_completo', models.CharField(max_length=255, verbose_name='Nombre Completo (Beneficiario)')),
                ('gestion', models.PositiveIntegerField(verbose_name='Gestión/Año')),
                ('categoria', models.CharField(help_text='Ej: 6to Secundaria, Promoción 2025, Docentes', max_length=100, verbose_name='Curso/Grado/Categoría')),
                ('tipo_pedido', models.CharField(choices=[('conjunto', 'Conjunto Completo'), ('separado', 'Prendas Separadas')], default='separado', max_length=20, verbose_name='Tipo de Pedido')),
                ('talla_conjunto', models.CharField(blank=True, choices=[('4', '4'), ('6', '6'), ('8', '8'), ('10', '10'), ('12', '12'), ('14', '14'), ('16', '16'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=5, null=True, verbose_name='Talla del Conjunto')),
                ('genero_conjunto', models.CharField(blank=True, choices=[('varon', 'Varón'), ('mujer', 'Mujer'), ('unisex', 'Unisex')], max_length=10, null=True, verbose_name='Género del Conjunto')),
                ('aporte', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('pagado', 'Pagado')], default='pendiente', max_length=20)),
                ('tipo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('qr', 'QR')], max_length=20, null=True)),
                ('estado_pedido', models.CharField(choices=[('registrado', 'Registrado'), ('en_produccion', 'En Producción'), ('entregado', 'Entregado')], default='registrado', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_personalizados', to='clientes.cliente', verbose_name='Institución / Cliente')),
            ],
            options={
                'verbose_name': 'Pedido Personalizado',
                'verbose_name_plural': 'Pedidos Personalizados',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedidoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('tipo_prenda', models.CharField(choices=[('chamarra', 'Chamarra'), ('buso', 'Buso'), ('polera', 'Polera'), ('short', 'Short')], max_length=20)),
                ('genero', models.CharField(choices=[('varon', 'Varón'), ('mujer', 'Mujer'), ('unisex', 'Unisex')], max_length=10)),
                ('talla', models.CharField(choices=[('4', '4'), ('6', '6'), ('8', '8'), ('10', '10'), ('12', '12'), ('14', '14'), ('16', '16'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=5)),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('es_generado_automaticamente', models.BooleanField(default=False)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos_personalizados.pedidopersonalizado')),
            ],
            options={
                'verbose_name': 'Ítem Personalizado',
                'verbose_name_plural': 'Ítems Personalizados',
                'ordering': ['tipo_prenda', 'genero', 'talla'],
            },
        ),
    ]
